# Generated by Django 3.2.4 on 2021-07-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='avatar.png', max_length=500, upload_to=''),
        ),
    ]
